### ISSUE TITLE
collectiveView, willDisplay

### ISSUE THREAD

**Issue by ofyzero** [Coder-TanJX/JXBanner#1]
Hi TanJX, 
I am trying to add video instead of image into the cell but have a problem with func collectionView(_ collectionView: UICollectionView,  willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath). 
I cannot run this function. I added this function to JXBanner, JXBannerDelegate. I am trying to run video when the related cell visible. 
Can you help me plz

**Comment by Coder-TanJX** [comment]
Hi TanJX,
Thank you for your feedback. Can you provide the screenshot or source code so that I can help you analyze the problem?

**Comment by Coder-TanJX** [comment]
> Hi TanJX,
> I am trying to add video instead of image into the cell but have a problem with func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath).
> I cannot run this function. I added this function to JXBanner, JXBannerDelegate. I am trying to run video when the related cell visible.
> Can you help me plz

----


Hi ofyzero,
Thank you for your feedback. Can you provide the screenshot or source code so that I can help you analyze the problem.

**Comment by ofyzero** [comment]
Thank you for quick response, i attached JXBanner and JXBannerDelegate
screenshot where i edited and source code of mine. Also , i added and
explanation at line 209.
Sincerely ,

**Comment by Coder-TanJX** [comment]
I can't see your screenshot and code, can you just send it to my email? (346417517 @qq.com)
