### ISSUE TITLE
当cell中imageView.contentMode = .scaleAspectFill时 

### ISSUE THREAD

**Issue by SmallMX** [Coder-TanJX/JXBanner#12]
Cell的Size会自适应图片尺寸，itemSize无效。是我设置问题吗？

**Comment by Coder-TanJX** [comment]
估计你的问题，你再看看吧

**Comment by PZXforXcode** [comment]
我也遇到这个问题了，设置为scaleAspectFill，size不对

**Comment by PZXforXcode** [comment]
> Cell的Size会自适应图片尺寸，itemSize无效。是我设置问题吗？

请问你解决了这个问题吗
