### ISSUE TITLE
pageControl.indicatorSize  无效，activeSize，inactiveSize，indicatorSize都无效！

### ISSUE THREAD

**Issue by SmallMX** [Coder-TanJX/JXBanner#13]
`func jxBanner(pageControl banner: JXBannerType, numberOfPages: Int, coverView: UIView, builder: JXBannerPageControlBuilder) -> JXBannerPageControlBuilder {
        let pageControl = JXPageControlChameleon()
        pageControl.contentMode = .right
        let size = CGSize(width: 3, height: 3)
        pageControl.activeSize = size
        pageControl.indicatorSize = size
        pageControl.inactiveSize = size
        pageControl.activeColor = UIColor(red: 16, green: 142, blue: 233)!
        pageControl.inactiveColor = .white
        pageControl.columnSpacing = 6
        pageControl.isAnimation = true
        builder.pageControl = pageControl
        builder.layout = {
            pageControl.snp.makeConstraints { (maker) in
                maker.left.right.equalTo(coverView).inset(10).priority(750)
                maker.bottom.equalTo(coverView.snp.bottom).inset(2)
                maker.height.equalTo(20)
            }
        }
        return builder
    }`

**Comment by Coder-TanJX** [comment]
"pageControl.indicatorSize = size“ ？？  indicatorSize不需要设置, 使用约束就行。
            builder.layout = {
                pageControl.snp.makeConstraints { (maker) in
                    maker.left.right.equalTo(coverView)
                    maker.top.equalTo(coverView.snp_bottom).offset(10)
                    maker.height.equalTo(20)
                }
            }

**Comment by SmallMX** [comment]
是activeSize，inactiveSize，indicatorSize都无效！

**Comment by SmallMX** [comment]
minIndicatorSize始终是10，10
