### ISSUE TITLE
#2269839 SIGBUS

### ISSUE THREAD

**Issue by zou145688zhuang** [Coder-TanJX/JXBanner#15]
机型：iPhone Xr 系统版本14.4 
JXPageControlScale里updateProgressyy12CoreGraphics7CGFloatVF + 1992 出现crash

libmecab.dylib
MeCab::TokenizerImpl<mecab_node_t, mecab_path_t>::lookup(char const*, char const*) + 340
19
UIKitCore
-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 660
20
CoreAutoLayout
0x0000000199050000 + 66844
21
UIKitCore
-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:] + 608
29
QuartzCore
CA::Transaction::commit() + 732

**Comment by Coder-TanJX** [comment]
同样系统，同样机型未复现。
