### ISSUE TITLE
JYPageControlScale指示器圆角可否外面控制

### ISSUE THREAD

**Issue by ccbq501** [Coder-TanJX/JXBanner#16]
JYPageControlScale.swift

**if isShowCorner {**
                if leftWidth > leftHeight {
                    leftLayer.cornerRadius = leftHeight*0.5
                }else {
                    leftLayer.cornerRadius = leftWidth*0.5
                }
                if rightWidth > rightHeight {
                    rightLayer.cornerRadius = rightHeight*0.5
                }else {
                    rightLayer.cornerRadius = rightWidth*0.5
                }
            **}**

**Comment by Coder-TanJX** [comment]
后边有空可以加一下外部圆角控制

**Comment by ccbq501** [comment]
666



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Coder-TanJX ***@***.***&gt;
发送时间: 2021年6月1日 09:52
收件人: Coder-TanJX/JXBanner ***@***.***&gt;
抄送: ccbq501 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Coder-TanJX/JXBanner] JYPageControlScale指示器圆角可否外面控制 (#16)





 
后边有空可以加一下外部圆角控制
