### ISSUE TITLE
iOS11系统，偶发闪退

### ISSUE THREAD

**Issue by Next-Future-X** [Coder-TanJX/JXBanner#18]
func scrollToIndexPath(_ indexPath: IndexPath, animated: Bool) { }
方法内部调用collectionView滚动方法，在系统版本低的设备上会触发闪退的情况。
断点分析为collectionView未刷新完成，调用scrollToItem导致。
解决办法：
我尝试在滚动之前，判断要求滚动到的index是否合法，且滚动到的位置是否有item，可以解决闪退问题
添加的判断代码如下：
guard collectionView.numberOfItems(inSection: indexPath.section) > indexPath.row, let _ = collectionView.dataSource?.collectionView(collectionView, cellForItemAt: indexPath) else { return }

![image](https://user-images.githubusercontent.com/18658063/123372719-a8577480-d5b6-11eb-8517-44fd372dfe91.png)

**Comment by Coder-TanJX** [comment]
好的，非常感谢提醒，虽然目前没有条件复现，但是今天我会更新一下代码。

**Comment by Coder-TanJX** [comment]
测试了一下你提供的代码会产生错误，params.cycleWay == .forward时不能自动滚动。

**Comment by Next-Future-X** [comment]
两个判断条件
第一 collectionView.numberOfItems(inSection: indexPath.section) > indexPath.row
第二 let _ = collectionView.dataSource?.collectionView(collectionView, cellForItemAt: indexPath)
请问是哪个条件卡住了

**Comment by Coder-TanJX** [comment]
可以帮我测试一下在：private func refreshData() 方法中使用下面代码吗？
 placeholderImgView.isHidden = pageCount > 0
        collectionView.performBatchUpdates {[weak self] in
            self?.collectionView.reloadData()
        } completion: { [weak self] _ in
            self?.reinitializeIndexPath()
        }

**Comment by Coder-TanJX** [comment]
对，就是第二个条件用这种循环滚动方式（params.cycleWay == .forward）会返回空。

**Comment by Next-Future-X** [comment]
params.cycleWay == .forward 这样设置的情况下是吧

**Comment by Coder-TanJX** [comment]
对，然后你使用我提供你的代码 看一下能解决你的问题吗

**Comment by Next-Future-X** [comment]
好的，我稍后试一下这段代码，测试设备在占用中

**Comment by Coder-TanJX** [comment]
<img width="1161" alt="WeChat53aabe6a1b96179285c607de4bb9eb53" src="https://user-images.githubusercontent.com/19760428/123943426-ba7a4e00-d9ce-11eb-99ac-388025ed6d8b.png">

**Comment by Next-Future-X** [comment]
我尝试添加performBatchUpdates方法，在 iOS11、12、14系统运行，目前没有发现crash问题了。

**Comment by Coder-TanJX** [comment]
好的 谢谢
