### ISSUE TITLE
轮播图不支持垂直滚动吗？scrollDirection = .vertical

### ISSUE THREAD

**Issue by ETmanwenhan** [Coder-TanJX/JXBanner#23]
只需要修改垂直参数，就可以实现了。望支持，谢谢！
JXBannerLayout中设置：scrollDirection = .vertical
JXBaseBanner类中修改：
            collectionView.scrollToItem(at: indexPath,
                                        at: .centeredVertically,
                                        animated: animated)

**Comment by Coder-TanJX** [comment]
好的，您的建议已经采纳，已增加垂直滚动功能，感谢你的反馈。
最近比较忙，只是简单测试了一下，
请帮助测试一下垂直滚动情况会不会产生新bug，多谢。
