### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by xudogn** [Coder-TanJX/JXBanner#25]
机型： iPhone 6
系统：11.2.1，12.5.5等
复现：基本功能使用，JXBanner(frame:), JXBannerCell。当只有1张图片时，cell向左偏移一半，仅显示右半部分。
多张图片则无此现象，其他机型也无此现象

**Comment by Coder-TanJX** [comment]
很抱歉，目前没有这样的测试环境，如果可以的话，希望您能帮忙修复一下，多谢~
