### ISSUE TITLE
能否支持上下滚动

### ISSUE THREAD

**Issue by OYForever** [Coder-TanJX/JXBanner#32]

**Comment by Coder-TanJX** [comment]
有的：JXBannerLayoutParams


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Coder-TanJX/JXBanner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 下午3:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Coder-TanJX/JXBanner] 能否支持上下滚动 (Issue #32)
