### ISSUE TITLE
10.3.1系统下 attempt to scroll to invalid index path

### ISSUE THREAD

**Issue by JWAutumn** [Coder-TanJX/JXBanner#4]

**Comment by Coder-TanJX** [comment]
> No description provided.

The description is not detailed enough to see the problem, please confirm whether it is used correctly.

**Comment by JWAutumn** [comment]
https://tva1.sinaimg.cn/large/007S8ZIlly1ggkq788yaxj32bu0imqqd.jpg

**Comment by JWAutumn** [comment]
https://tva1.sinaimg.cn/large/007S8ZIlly1ggkqajra5xj30sc0ba402.jpg
it's worked....

**Comment by Coder-TanJX** [comment]
> https://tva1.sinaimg.cn/large/007S8ZIlly1ggkq788yaxj32bu0imqqd.jpg

只有10.3.1系统有这个问题吗, 能提供能复现的测试代码吗?

**Comment by JWAutumn** [comment]
我是在测试SE兼容性的时候意外发现这个问题的。。。
13系统上没遇到这个问题。所以也不太确定其他系统
查到的关于“attempt to scroll to invalid index path”出现的问题是： collectionView的scrollToItem(at:xxx)方法在调用之前要先调用collectionView的reloadData()方法。
我没有修改源代码进行测试，只是获取到接口数据后，延迟了0.2s调用了banner的reloadView()方法。

**Comment by Coder-TanJX** [comment]
正常设置collectionView.dataSource的时候会自动reloadData()

**Comment by JWAutumn** [comment]
是的, 我查到的解决方法大致如下：
UIView.animate(withDuration: 0.0, animations: {UICollectionView.reloadData()}) { (finish) in
    if finish {
        UICollectionView.scrollToItem(at: index, at: .centeredHorizontally, animated: true)
    }
}

**Comment by Coder-TanJX** [comment]
这个解决方案不好, 不能每次滚动Cell都UICollectionView.reloadData()

**Comment by JWAutumn** [comment]
嗯，大佬就请尝试测试并解决一下这个问题。有了好的解决方案。麻烦告诉我一声。多谢了

**Comment by Coder-TanJX** [comment]
好的, 多谢提出问题.
