### ISSUE TITLE
how to setIndex manually in code

### ISSUE THREAD

**Issue by xuanwenchao** [Coder-TanJX/JXBanner#5]
after pod JXBanner to my code , but i can't change the banner index manually in my code.
eg. 
    lazy var banner: JXBanner = {
        let banner = JXBanner()
        banner.backgroundColor = UIColor.clear
        banner.delegate = self
        banner.dataSource = self
        return banner
    }()

==========================
self.banner.setCurrentIndex(1)  //it is coun't work

may i access  property currentIndexPath to change?

thank you.

**Comment by Coder-TanJX** [comment]
> after pod JXBanner to my code , but i can't change the banner index manually in my code.
> eg.
> lazy var banner: JXBanner = {
> let banner = JXBanner()
> banner.backgroundColor = UIColor.clear
> banner.delegate = self
> banner.dataSource = self
> return banner
> }()
> 
> ==========================
> self.banner.setCurrentIndex(1) //it is coun't work
> 
> may i access property currentIndexPath to change?
> 
> thank you.


This feature is not currently available, but will be added later
