### ISSUE TITLE
pageCount == 1 cell的坐标会偏移

### ISSUE THREAD

**Issue by qiven** [Coder-TanJX/JXBanner#6]
class JXDefaultVC: UIViewController {
    
    var pageCount = 1

<img width="450" alt="截屏2020-09-21 上午11 04 40" src="https://user-images.githubusercontent.com/19283754/93730232-52eed100-fbfa-11ea-891d-06a9224944de.png">

**Comment by Coder-TanJX** [comment]
JXDefaultVC下的banner是通过Xib自动布局,
 所以"viewDidLoad"加载banner时拿到的JXDefaultVC.view的frame不对, 显示偏移.
 JXDefaultVC加上如下代码就好了
感谢回馈

```
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        banner.reloadView()
    }

```

**Comment by Coder-TanJX** [comment]
最新0.3.2版本已经修复此bug
