### ISSUE TITLE
数据源只有一个的时候cell会向左偏移

### ISSUE THREAD

**Issue by qiven** [Coder-TanJX/JXBanner#7]
<img width="450" alt="截屏2020-09-21 上午11 04 40" src="https://user-images.githubusercontent.com/19283754/93842243-c0693300-fcc8-11ea-991d-0d4e08c1bda3.png">

**Comment by Coder-TanJX** [comment]
??

**Comment by Coder-TanJX** [comment]
0.3.2版本已经修复了
